org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=true
android.compileSdk=34
android.minSdk=24
android.targetSdk=34

kotlin.code.style=official
kotlin.js.ir.binaries=true

# Disable old dependency API
systemProp.org.gradle.internal.publish.checksums.insecure=true
